### ISSUE TITLE
sed slash delimiter collision with branch name in gitflow convention

### ISSUE THREAD

**Issue by bobo96run** [jan-matejka/git-branch-backup#2]
Hi,

Thank you for this useful little tool!

I follow gitflow convention, with branch name using a slash "/" for hierarchy, e.g. "feature/KEY-123_branchName"

Unfortunately, the slash conflicts with the `sed` command in this script:

> sed: 1: "s/^..feature/KEY-123_br ...": bad flag in substitute command: '/'

therefore it does not detect other backup branches already present, and tries to re-create backup1, which fails.

Fortunately, sed can accept many other characters as delimiters in its pattern, so we can just replace it by another character which is illegal within a git branch name, to ensure we avoid any other potential collision https://git-scm.com/docs/git-check-ref-format#_description

> They cannot have [...] space, tilde ~, caret ^, or colon : anywhere.

so using e.g. a colon : works just fine!

**Comment by jan-matejka** [comment]
Thanks for the report. I actually had it fixed for years but forgot to push it lmao
